In [21]:
import pandas as pd
from datetime import datetime
df = pd.read_json('./data.json')

,esg,esg_industry,industry,name,ticker
0,[],[],Mining (except Oil & Gas),20-Microns-Ltd,20MICRONS
1,"[[1622505600000, 14.44], [1625097600000, 14.46...","[[1622505600000, 13.83], [1625097600000, 12.9]...",Containers & Packaging Manufacturing,3M-INDIA-LIMITED,3MINDIA
2,"[[1633046400000, 36.21], [1635724800000, 35.68...","[[1633046400000, 19.939999999999998], [1635724...",Brokerage & Capital Markets,5paisa-Capital-Limited,5PAISA
3,[],[],Brokerage & Capital Markets,A-K-CAPITAL-SERVICES-LIMITED,530499
4,[],[],"Architectural, Engineering, & Related Services",A2Z-MAINTENANCE-and-ENGINEERING-SERVICES-LIMITED,A2ZINFRA
5,"[[1622505600000, 16.98], [1625097600000, 17.08...","[[1622505600000, 26.05], [1625097600000, 26.41...",Health Care & Pharmaceuticals,Aarti-Drugs-Ltd,AARTIDRUGS
6,"[[1622505600000, 19.55], [1625097600000, 19.68...","[[1622505600000, 28.24], [1625097600000, 26.97...","Chemicals, Plastics & Rubber Products Mfg.",AARTI-INDUSTRIES-LTD,AARTIIND
7,[],[],"Chemicals, Plastics & Rubber Products Mfg.",Aarti-Surfactants-Ltd,AARTISUR
8,"[[1625097600000, 52.959999999999994], [1627776...","[[1625097600000, 66.0], [1627776000000, 73.21]...",Real Estate Financial Services,Aavas-Financiers-Ltd,AAVAS
9,[],[],Oil and Gas Extraction,ABAN-OFFSHORE,ABAN
10,"[[1619827200000, 98.83], [1622505600000, 97.0]...","[[1619827200000, 99.52], [1622505600000, 98.11...","Electronic Equipment & Instrumentation, Energy...",ABB-in-India,ABB
11,"[[1622505600000, 55.22], [1625097600000, 54.85...","[[1622505600000, 71.43], [1625097600000, 70.73...",Health Care & Pharmaceuticals,Abbott-India-Ltd,ABBOTINDIA
12,[],[],"Airport, Harbor Operations, & Logistics",ABC-India-Ltd,ABCI
13,[],[],IT & Network Services,ABM-Knowledgeware-Ltd,ECM
14,"[[1619827200000, 75.22999999999999], [16225056...","[[1619827200000, 70.74000000000001], [16225056...",Construction Materials,ACC-LIMITED,ACC
15,[],[],IT & Network Services,Accelya-Kale-Solutions-Ltd,ACCELYA
16,[],[],Manufacturing,Acrysil-Ltd,ACRY
17,"[[1672531200000, 17.29], [1675209600000, 15.6]...","[[1672531200000, 22.49], [1675209600000, 21.15...",Machinery Manufacturing,Action-Construction-Equipment-Ltd,ACE
18,"[[1619827200000, 72.41], [1622505600000, 72.45...","[[1619827200000, 59.78], [1622505600000, 60.87...",Conglomerates,Adani-Enterprises-Limited,AWL
19,"[[1625097600000, 57.550000000000004], [1627776...","[[1625097600000, 49.33], [1627776000000, 27.27...",Utilities,Adani-Gas-Ltd,ATGL

In [22]:
def conv_to_datetime(series):
    for lst in series:
        for t_e in lst:
            t_e[0] = pd.to_datetime(t_e[0], unit='ms')

In [24]:
conv_to_datetime(df['esg'])
conv_to_datetime(df['esg_industry'])
df

,esg,esg_industry,industry,name,ticker
0,[],[],Mining (except Oil & Gas),20-Microns-Ltd,20MICRONS
1,"[[2021-06-01 00:00:00, 14.44], [2021-07-01 00:...","[[2021-06-01 00:00:00, 13.83], [2021-07-01 00:...",Containers & Packaging Manufacturing,3M-INDIA-LIMITED,3MINDIA
2,"[[2021-10-01 00:00:00, 36.21], [2021-11-01 00:...","[[2021-10-01 00:00:00, 19.939999999999998], [2...",Brokerage & Capital Markets,5paisa-Capital-Limited,5PAISA
3,[],[],Brokerage & Capital Markets,A-K-CAPITAL-SERVICES-LIMITED,530499
4,[],[],"Architectural, Engineering, & Related Services",A2Z-MAINTENANCE-and-ENGINEERING-SERVICES-LIMITED,A2ZINFRA
5,"[[2021-06-01 00:00:00, 16.98], [2021-07-01 00:...","[[2021-06-01 00:00:00, 26.05], [2021-07-01 00:...",Health Care & Pharmaceuticals,Aarti-Drugs-Ltd,AARTIDRUGS
6,"[[2021-06-01 00:00:00, 19.55], [2021-07-01 00:...","[[2021-06-01 00:00:00, 28.24], [2021-07-01 00:...","Chemicals, Plastics & Rubber Products Mfg.",AARTI-INDUSTRIES-LTD,AARTIIND
7,[],[],"Chemicals, Plastics & Rubber Products Mfg.",Aarti-Surfactants-Ltd,AARTISUR
8,"[[2021-07-01 00:00:00, 52.959999999999994], [2...","[[2021-07-01 00:00:00, 66.0], [2021-08-01 00:0...",Real Estate Financial Services,Aavas-Financiers-Ltd,AAVAS
9,[],[],Oil and Gas Extraction,ABAN-OFFSHORE,ABAN
10,"[[2021-05-01 00:00:00, 98.83], [2021-06-01 00:...","[[2021-05-01 00:00:00, 99.52], [2021-06-01 00:...","Electronic Equipment & Instrumentation, Energy...",ABB-in-India,ABB
11,"[[2021-06-01 00:00:00, 55.22], [2021-07-01 00:...","[[2021-06-01 00:00:00, 71.43], [2021-07-01 00:...",Health Care & Pharmaceuticals,Abbott-India-Ltd,ABBOTINDIA
12,[],[],"Airport, Harbor Operations, & Logistics",ABC-India-Ltd,ABCI
13,[],[],IT & Network Services,ABM-Knowledgeware-Ltd,ECM
14,"[[2021-05-01 00:00:00, 75.22999999999999], [20...","[[2021-05-01 00:00:00, 70.74000000000001], [20...",Construction Materials,ACC-LIMITED,ACC
15,[],[],IT & Network Services,Accelya-Kale-Solutions-Ltd,ACCELYA
16,[],[],Manufacturing,Acrysil-Ltd,ACRY
17,"[[2023-01-01 00:00:00, 17.29], [2023-02-01 00:...","[[2023-01-01 00:00:00, 22.49], [2023-02-01 00:...",Machinery Manufacturing,Action-Construction-Equipment-Ltd,ACE
18,"[[2021-05-01 00:00:00, 72.41], [2021-06-01 00:...","[[2021-05-01 00:00:00, 59.78], [2021-06-01 00:...",Conglomerates,Adani-Enterprises-Limited,AWL
19,"[[2021-07-01 00:00:00, 57.550000000000004], [2...","[[2021-07-01 00:00:00, 49.33], [2021-08-01 00:...",Utilities,Adani-Gas-Ltd,ATGL